resolver: nightly-2016-08-19
packages:
- '.'
- '/home/james/code/forks/haskell/core-erlang'
extra-deps:
- text-conversions-0.3.0  
- transformers-abort-0.5.0.1
- freer-0.2.3.0
flags: {}
extra-package-dbs: []
# compiler-check: newer-minor
