resolver: lts-6.3
# User packages to be built.
# Various formats can be used as shown in the example below.
# 
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
# 
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- '.'
- '/home/james/code/forks/haskell/core-erlang'
extra-deps:
- text-conversions-0.3.0  
- transformers-abort-0.5.0.1
flags: {}
extra-package-dbs: []
# compiler-check: newer-minor
